global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['13.232.88.168:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['13.232.88.168:9100']
